In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/3D Printing Project - Sheet1.csv')

In [ ]:
print(data)

       Material  Scan Speed (mm/s)  Hatch Distance (mm)  Laser Power (Watts)  \
0         IN718              750.0                0.090                250.0   
1         IN718              850.0                0.090                250.0   
2         IN718              950.0                0.090                250.0   
3         IN718             1050.0                0.090                250.0   
4         IN718             1150.0                0.090                250.0   
..          ...                ...                  ...                  ...   
220  AlSiMg0.75              650.0                0.085                150.0   
221  AlSiMg0.75              650.0                0.085                150.0   
222  AlSiMg0.75              650.0                0.085                150.0   
223  AlSiMg0.75              650.0                0.085                150.0   
224  AlSiMg0.75              650.0                0.085                150.0   

     Densification  
0         0.992579

In [ ]:
data = data.sample(frac = 1)
print(data)

       Material  Scan Speed (mm/s)  Hatch Distance (mm)  Laser Power (Watts)  \
217  AlSiMg0.75             650.00              0.05977                150.0   
216  AlSiMg0.75             902.27              0.08500                150.0   
85        IN718             750.00              0.11000                325.0   
83        IN718            1050.00              0.10000                325.0   
79        IN718            1150.00              0.09000                325.0   
..          ...                ...                  ...                  ...   
157    Al-50%Si            1200.00              0.15000                330.0   
173    Al-50%Si            1000.00              0.12000                320.0   
134    Al-50%Si             950.00              0.15000                340.0   
151    Al-50%Si            1000.00              0.11000                310.0   
28        IN718            1050.00              0.09000                275.0   

     Densification  
217       0.979300

In [ ]:
print(data['Material'].unique())

['AlSiMg0.75' 'IN718' 'Al-50%Si']


In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['Material']= label_encoder.fit_transform(data['Material'])
print(data)

     Material  Scan Speed (mm/s)  Hatch Distance (mm)  Laser Power (Watts)  \
217         1             650.00              0.05977                150.0   
216         1             902.27              0.08500                150.0   
85          2             750.00              0.11000                325.0   
83          2            1050.00              0.10000                325.0   
79          2            1150.00              0.09000                325.0   
..        ...                ...                  ...                  ...   
157         0            1200.00              0.15000                330.0   
173         0            1000.00              0.12000                320.0   
134         0             950.00              0.15000                340.0   
151         0            1000.00              0.11000                310.0   
28          2            1050.00              0.09000                275.0   

     Densification  
217       0.979300  
216       0.980000  


In [ ]:
x = data.drop(['Densification'], axis = 1)
print(x)

     Material  Scan Speed (mm/s)  Hatch Distance (mm)  Laser Power (Watts)
217         1             650.00              0.05977                150.0
216         1             902.27              0.08500                150.0
85          2             750.00              0.11000                325.0
83          2            1050.00              0.10000                325.0
79          2            1150.00              0.09000                325.0
..        ...                ...                  ...                  ...
157         0            1200.00              0.15000                330.0
173         0            1000.00              0.12000                320.0
134         0             950.00              0.15000                340.0
151         0            1000.00              0.11000                310.0
28          2            1050.00              0.09000                275.0

[225 rows x 4 columns]


In [ ]:
y = data[['Densification']]
print(y)

     Densification
217       0.979300
216       0.980000
85        0.994647
83        0.989173
79        0.994039
..             ...
157       0.985200
173       0.988800
134       0.990800
151       0.983600
28        0.994891

[225 rows x 1 columns]


In [ ]:
x = x.astype(float)
y = y.astype(float)
print(x.dtypes)
print(y.dtypes)

Material               float64
Scan Speed (mm/s)      float64
Hatch Distance (mm)    float64
Laser Power (Watts)    float64
dtype: object
Densification    float64
dtype: object


In [ ]:
x = x.to_numpy()
y = y.to_numpy()

In [ ]:
print(x)
print(y)

[[1.0000e+00 6.5000e+02 5.9770e-02 1.5000e+02]
 [1.0000e+00 9.0227e+02 8.5000e-02 1.5000e+02]
 [2.0000e+00 7.5000e+02 1.1000e-01 3.2500e+02]
 [2.0000e+00 1.0500e+03 1.0000e-01 3.2500e+02]
 [2.0000e+00 1.1500e+03 9.0000e-02 3.2500e+02]
 [2.0000e+00 9.5000e+02 1.3000e-01 2.7500e+02]
 [2.0000e+00 8.5000e+02 1.1000e-01 3.2500e+02]
 [2.0000e+00 1.1500e+03 9.0000e-02 2.5000e+02]
 [2.0000e+00 8.5000e+02 1.3000e-01 3.2500e+02]
 [2.0000e+00 1.1500e+03 1.0000e-01 3.2500e+02]
 [2.0000e+00 7.5000e+02 1.0000e-01 3.5000e+02]
 [2.0000e+00 7.5000e+02 1.2000e-01 3.2500e+02]
 [2.0000e+00 1.0500e+03 1.2000e-01 2.5000e+02]
 [0.0000e+00 9.5000e+02 1.1000e-01 3.2000e+02]
 [2.0000e+00 1.0500e+03 1.0000e-01 2.5000e+02]
 [0.0000e+00 1.4000e+03 1.5000e-01 3.1000e+02]
 [0.0000e+00 1.1000e+03 1.5000e-01 3.3000e+02]
 [2.0000e+00 1.0500e+03 1.1000e-01 3.2500e+02]
 [2.0000e+00 9.5000e+02 1.2000e-01 3.5000e+02]
 [0.0000e+00 8.0000e+02 1.5000e-01 3.7000e+02]
 [2.0000e+00 8.5000e+02 1.1000e-01 2.7500e+02]
 [2.0000e+00 

In [ ]:
from sklearn.model_selection import train_test_split

train_x, test_x = train_test_split(x, test_size=0.2)
train_y, test_y = train_test_split(y, test_size=0.2)

In [ ]:
from keras import models
from keras import layers
from keras import regularizers
from keras.layers import Dense, Activation, Flatten

In [ ]:
model = models.Sequential()
model.add(Dense(128, kernel_initializer='normal',input_dim = train_x.shape[1], activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))


In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mape'])

In [ ]:
history = model.fit(train_x, train_y, epochs = 500, batch_size = 50)

Epoch 1/500
4/4 [==============================] - 1s 7ms/step - loss: 3.5131 - mape: 127.8749
Epoch 2/500
4/4 [==============================] - 0s 6ms/step - loss: 0.4072 - mape: 55.2539
Epoch 3/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1015 - mape: 25.9019
Epoch 4/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0620 - mape: 21.1652
Epoch 5/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0439 - mape: 16.9580
Epoch 6/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0390 - mape: 16.1007
Epoch 7/500
4/4 [==============================] - 0s 7ms/step - loss: 0.0343 - mape: 14.9039
Epoch 8/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0308 - mape: 14.2494
Epoch 9/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0294 - mape: 13.6360
Epoch 10/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0296 - mape: 13.8163
Epoch 11/500
4/4 [==============================] - 0s 7m

In [ ]:
pred_test = model.predict(test_x)
pred_train = model.predict(train_x)

In [ ]:
from keras import losses

In [ ]:
mape = losses.MeanAbsolutePercentageError()

In [ ]:
test_error = mape(test_y,pred_test)
train_error = mape(train_y, pred_train)

In [ ]:
print("Training Error: ", train_error)
print("Testing Error: ", test_error)

Training Error:  tf.Tensor(0.58281106, shape=(), dtype=float32)
Testing Error:  tf.Tensor(0.64660424, shape=(), dtype=float32)


In [ ]:
print(pred_train)
print(pred_test)

[[0.9913718 ]
 [0.994923  ]
 [0.9846632 ]
 [0.9963587 ]
 [0.9922768 ]
 [0.9849552 ]
 [0.9905196 ]
 [0.990877  ]
 [0.9956625 ]
 [0.99225336]
 [0.98961157]
 [0.99035686]
 [0.99457324]
 [0.9936381 ]
 [0.9922665 ]
 [0.99125284]
 [0.991461  ]
 [0.9912434 ]
 [0.99222773]
 [0.9926384 ]
 [0.9913709 ]
 [0.9911358 ]
 [0.9913737 ]
 [0.989627  ]
 [0.98995   ]
 [0.99315554]
 [0.9924799 ]
 [0.9894413 ]
 [0.99223536]
 [0.9949318 ]
 [0.99526924]
 [0.99227166]
 [0.98961645]
 [0.9880056 ]
 [0.9908736 ]
 [0.9945783 ]
 [0.9898028 ]
 [0.99064773]
 [0.9933515 ]
 [0.990458  ]
 [0.98984164]
 [0.9949348 ]
 [0.99125046]
 [0.98957944]
 [0.98932046]
 [0.9885926 ]
 [0.98984176]
 [0.9926306 ]
 [0.9893679 ]
 [0.99135727]
 [0.9952658 ]
 [0.9922239 ]
 [0.98495084]
 [0.99351186]
 [0.992956  ]
 [0.9903256 ]
 [0.98827976]
 [0.99461025]
 [0.9893171 ]
 [0.9932318 ]
 [0.9899513 ]
 [0.99152356]
 [0.99087185]
 [0.9906217 ]
 [0.989842  ]
 [0.991247  ]
 [0.9924904 ]
 [0.9880408 ]
 [0.98353237]
 [0.9945707 ]
 [0.9945877 ]
 [0.98

In [ ]:
print(train_y)
print(test_y)

[[0.99343066]
 [0.99233577]
 [0.9554    ]
 [0.993309  ]
 [0.9805    ]
 [0.988     ]
 [0.9868    ]
 [0.9946472 ]
 [0.99367397]
 [0.99      ]
 [0.99476886]
 [0.99087591]
 [0.99270073]
 [0.99513382]
 [0.9959854 ]
 [0.9896    ]
 [0.9808    ]
 [0.9868    ]
 [0.9839    ]
 [0.99233577]
 [0.9716    ]
 [0.99610706]
 [0.9896    ]
 [0.99306569]
 [0.9848    ]
 [0.99136253]
 [0.98832117]
 [0.98953771]
 [0.9788    ]
 [0.99014598]
 [0.9847    ]
 [0.9912    ]
 [0.99136253]
 [0.9836    ]
 [0.9808    ]
 [0.99476886]
 [0.9832    ]
 [0.99428224]
 [0.99610706]
 [0.9838    ]
 [0.982     ]
 [0.99756691]
 [0.99476886]
 [0.9908    ]
 [0.98990268]
 [0.9819    ]
 [0.9747    ]
 [0.9959854 ]
 [0.98990268]
 [0.974     ]
 [0.99403893]
 [0.99635036]
 [0.99659367]
 [0.9888    ]
 [0.99452555]
 [0.9888    ]
 [0.99452555]
 [0.99221411]
 [0.984     ]
 [0.99525547]
 [0.99586375]
 [0.99708029]
 [0.9868    ]
 [0.9904    ]
 [0.9824    ]
 [0.9868    ]
 [0.99586375]
 [0.99148419]
 [0.9765    ]
 [0.99160584]
 [0.99184915]
 [0.99

In [ ]:
import pickle
pickle.dump(model, open('project.pkl','wb'))

INFO:tensorflow:Assets written to: ram://ca0f9dc0-d0c4-4833-b35c-17b3ae3313e8/assets


INFO:tensorflow:Assets written to: ram://ca0f9dc0-d0c4-4833-b35c-17b3ae3313e8/assets
